### ISSUE TITLE
Laravel Wrapper

### ISSUE THREAD

**Issue by montyclt** [spiritix/php-chrome-html2pdf#1]
I created a Laravel Wrapper

https://github.com/montyclt/laravel-chrome-html2pdf

Is not in composer now, but I will publish in the next days.

**Comment by spiritix** [comment]
Good to see that you find this library useful mate, I am sure the Laravel community will appreciate the wrapper. If you find any issues or bugs in the converter please let me know, I'd like to publish a stable version as soon as possible.
