### ISSUE TITLE
npm WARN Invalid version: "1.4"

### ISSUE THREAD

**Issue by perice** [spiritix/php-chrome-html2pdf#13]
Hi,

since updating to version 1.4, I'm getting this error:

npm WARN Invalid version: "1.4"
npm WARN php-chrome-html2pdf No description
npm WARN php-chrome-html2pdf No repository field.
npm WARN php-chrome-html2pdf No README data
npm WARN php-chrome-html2pdf No license field.

If I change the version from "1.4" to "1.4.0" in package.json, it works.

Best,
Peter

**Comment by spiritix** [comment]
Are you trying to install the package directly from NPM? Actually this is a PHP package and should only be installed using Composer.

**Comment by perice** [comment]
Nope, just running "composer update" gives me that error.

**Comment by spiritix** [comment]
I see. Fixing in today's release.
