### ISSUE TITLE
External CSS not applied

### ISSUE THREAD

**Issue by PostavkiExpert** [spiritix/php-chrome-html2pdf#25]
I am trying to make PDF from page of my site.
All external css have full path (//domain/path.css).
Generated PDF has no styles from css.

**Comment by PostavkiExpert** [comment]
Links started with // not work

**Comment by PostavkiExpert** [comment]
Awesome project! Thanks to contributors!

**Comment by spiritix** [comment]
Thanks, glad to hear that you like it!
