### ISSUE TITLE
Version no longer supported. Upgrade to @latest

### ISSUE THREAD

**Issue by NiklasBr** [spiritix/php-chrome-html2pdf#37]
Upon installation we get the following error: `npm WARN deprecated puppeteer@3.3.0: Version no longer supported. Upgrade to @latest`

Are there any plans on offering a [newer version](https://www.npmjs.com/package/puppeteer)?

**Comment by spiritix** [comment]
Hi @NiklasBr, a new version with updated dependencies is in progress. Coming in ~1 week.

**Comment by spiritix** [comment]
Took a bit longer than expected. Check it out. https://github.com/spiritix/php-chrome-html2pdf/releases/tag/v1.7

**Comment by NiklasBr** [comment]
Thanks! Will try it asap.

**Comment by NiklasBr** [comment]
Worked great, thanks again!
