### ISSUE TITLE
npm WARN Invalid version: "1.7"

### ISSUE THREAD

**Issue by hedasp** [spiritix/php-chrome-html2pdf#43]
Ref issue #13 
Hi, having issues with composer update after upgrade to 1.7.1
npm WARN Invalid version: "1.7"
npm WARN php-chrome-html2pdf No description
npm WARN php-chrome-html2pdf No repository field.
npm WARN php-chrome-html2pdf No README data
npm WARN php-chrome-html2pdf No license field.

Same as with 1.4, it resolved after updating package.json from 1.7 to 1.7.1

**Comment by spiritix** [comment]
These should just be warnings, you can ignore them
