### ISSUE TITLE
style markup issues in combination with <table>

### ISSUE THREAD

**Issue by mvaDevelop** [spiritix/php-chrome-html2pdf#46]
Noticed some issues with table in htlm2pdf documents which I can't seem to fix. These are the issues I get:

- borders seem to disappear  at random locations. If i view the page as html i have a nicely formatted table without border breaks. If i then convert the html to pdf, i get strange line breaks:
as html: 
![afbeelding](https://user-images.githubusercontent.com/116262815/198578547-5c03c69a-c262-4a54-84e2-aff0be2eebd8.png)
as pdf:
![afbeelding](https://user-images.githubusercontent.com/116262815/198578579-bc77518d-27af-4888-ae94-1718adc67803.png)
note: in my pdf the user can set the amount of copies, which will duplicate the table x amount of times. In the duplicates i have no issue with border breaks so it seems to happen randomly

- div below the table sometimes overflows into the table footer. This also seems to happen randomly, and when i view the document as html i see no issues.
![afbeelding](https://user-images.githubusercontent.com/116262815/198579193-e579b1be-b1ed-45b8-9979-cb339f56764d.png)

Any ideas what the issue could be here? Are there known bugs in combining html2pdf with table html? I did notice that these bugs occur when the table spans over multiple pages

Thanks in advance for any help you can provide!

**Comment by spiritix** [comment]
Can you please try to print (CTRL+P) your page in Chrome web browser and save it to PDF? Are there any differences to the PDF generated by this library?

**Comment by mvaDevelop** [comment]
The border break seems to happen at the exact same coordinate (this is on a different tr in standard pdf as it doesn't calculate the same margins)

The collapsing into the table footer doesn't seem to happen in standard pdf. However, the margin between the div and the tfoot is a lot bigger than in html2pdf

**Comment by spiritix** [comment]
Can you try to set the `mediaType` option to `screen` or `null`? Very often, Chrome renders elements differently if media type is set to `print`, which it is by default. But other than that, there are some general differences in rendering compared to the web version, which are caused by Chrome. The only way to fix them is to apply custom CSS that's only applied to the print version (then you would have to revert to mediaType print).

**Comment by mvaDevelop** [comment]
> 

This results in the exact same border breaks

**Comment by spiritix** [comment]
Please create a new issue for the Puppeteer repository. Such issues are caused by their PDF rendering engine, there's not much I can do about it, unfortunately.

https://github.com/puppeteer/puppeteer/issues
