### ISSUE TITLE
Headers displayed in PDF

### ISSUE THREAD

**Issue by Shotman** [spiritix/php-chrome-html2pdf#49]
I have this 

> HTTP/1.0 200 OK Cache-Control: no-cache, private Date: Tue, 06 Dec 2022 10:21:31 GMT

displayed at the top of my PDF and looking through issues/docs and pupeteer docs I don't how I can disable that, anyone have any insight ?

**Comment by spiritix** [comment]
That's an issue in your backend, not related to this library. Probably something like this: https://github.com/KnpLabs/KnpSnappyBundle/issues/19
