### ISSUE TITLE
Unable to install on Linux Server

### ISSUE THREAD

**Issue by iabhitech** [spiritix/php-chrome-html2pdf#51]
I have successfully added the library in the PHP project but on the server, I'm unable to install this library.

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

![image](https://user-images.githubusercontent.com/43298099/216594195-d54b8dab-c4fa-490e-a9a9-aa45f56dc003.png)

**Comment by spiritix** [comment]
As the message says, this is an optional dependency. The library should work without it.
