### ISSUE TITLE
Uncaught PHP Exception: Shell error: 133

### ISSUE THREAD

**Issue by agendartobias** [spiritix/php-chrome-html2pdf#52]
Hey, any idea why do i get this error:

`Uncaught PHP Exception Spiritix\Html2Pdf\ConverterException: "Shell error: 133" at /var/www/vhosts/pimcorex/vendor/spiritix/php-chrome-html2pdf/src/Spiritix/Html2Pdf/Converter.php line 192 {"exception":"[object] (Spiritix\\Html2Pdf\\ConverterException(code: 0): Shell error: 133 at /var/www/vhosts/pimcorex/vendor/spiritix/php-chrome-html2pdf/src/Spiritix/Html2Pdf/Converter.php:192)"} []`

**Comment by spiritix** [comment]
Never saw this error code before... Did you install the dependencies as listed here? https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

**Comment by 91320113** [comment]
Same Error here!

**Comment by 91320113** [comment]
I'm using Almalinux 8, SELinux was preventing nodejs from accessing execmem, disabling SELinux to test, and it works.

Please note that it's not recommended to disable SELinux in a production environment.

**Comment by agendartobias** [comment]
@91320113 i can confirm that the problem was SELinux - thank you!

We made two modification to the config and now it works with SELinux on:

`audit2allow -M spiritix-php-chrome-html2pdf
semodule -i spiritix-php-chrome-html2pdf.pp`
