### ISSUE TITLE
Shell error 127 on linux ECS aws server but works fine on local

### ISSUE THREAD

**Issue by codinglife456** [spiritix/php-chrome-html2pdf#53]
The library works fine on local host however after pushing it to the production branch and running `composer require spiritix/php-chrome-html2pdf`, I am now receiving shell error 127
```
                    $stringInput = new StringInput();
                    $stringInput->setHtml($html_of_page);
                    $converter = new Converter($stringInput, new StringOutput());
                    $converter->setOptions([
                        'printBackground' => true, //Print background is required to have background color styling take effect
                        'displayHeaderFooter' => true,
                        'format' => "A4",
                        'headerTemplate' => '<div></div>',
                        'footerTemplate' => '<div style="margin: 0px 40px; display:flex; align-items:flex-end; align-content:flex-end; justify-content:flex-end ; width:100vw!important; font-size:10px !important;"><p class="pageNumber"></p><p>/</p><p class="totalPages"></p></div>',
                        'margin' => ['top' => '40px', 'bottom' => '70px', 'left' => '40px', 'right' => '40px']
                        ]);
                    $converter_output = $converter->convert();
```

Error message
` production.ERROR: Shell error: 127 {"exception":"[object] (Spiritix\\Html2Pdf\\ConverterException(code: 0): Shell error: 127 at /var/www/html/vendor/spiritix/php-chrome-html2pdf/src/Spiritix/Html2Pdf/Converter.php:$
[stacktrace]
`

Attempted solutions
1) I have tried changing permissions and ownership to the Converter.php file however the error remains
![image](https://user-images.githubusercontent.com/77308867/232713157-c93376bd-fc41-46e7-91df-27be32ec620d.png)

2) I have also tried to specify the filepath of node 
`$converter->setNodePath('/home/ec2user/.nvm/versions/node/v10.16.0/bin');` however this results in shell error 126 but upon inspecting the permission node it is already `-rwxrwxr-x 1 ec2-user ec2-user 41115408 May 28  2019 node`

**Comment by MarcPinnell** [comment]
Any solution found for this? Getting the same error on a Linux install.

**Comment by codinglife456** [comment]
Yup, managed to resolve it by changing the executable permission allowing access to apache on /home/ec2user which previously wasn't granted

**Comment by spiritix** [comment]
Manually set the path to your Node.js executable using the $converter->setNodePath() method.

**Comment by sindev95** [comment]
> Manually set the path to your Node.js executable using the $converter->setNodePath() method.

even if you set the path and with correct permission it didn't work for some reason especially on EC2 RHEL , any other EC2 instances works fine 

main issue is RHEL doesn't grant permission for node to execute for god knows why even if it has the needed permission while it works fine on other os
