### ISSUE TITLE
Shell error: 127 When Trying to Convert

### ISSUE THREAD

**Issue by ethanbeyer** [spiritix/php-chrome-html2pdf#6]
Hello,

I'm trying to get this working within a Scotchbox VM, and for some reason it won't execute the `->convert()` command.

My Code:
```php
use Spiritix\Html2Pdf\Converter;
use Spiritix\Html2Pdf\Input\StringInput;
use Spiritix\Html2Pdf\Output\FileOutput;

$input = new StringInput();
$input->setHtml(file_get_contents('./html/letter.html'));

$converter = new Converter($input, new FileOutput());
// $converter->setNodePath('/home/vagrant/.nvm/versions/node/v6.10.3/bin/node');
$converter->setOption('landscape', true);
$converter->setOptions([
    'printBackground' => true,
    'headerTemplate' => '<p>I am a header</p>',
]);


$output = $converter->convert();
$output->store(dirname(__FILE__) . '/out/' . date('h-m') . '.pdf');
```

As you can see, there's a comment to define the Node Path. If I un-comment that, I get this output:

```
Uncaught Spiritix\Html2Pdf\ConverterException:
    Binary error: (node:2813) UnhandledPromiseRejectionWarning:
    Unhandled promise rejection (rejection id: 1): Error: spawn EACCES in /var/www/public/vendor/spiritix/php-chrome-html2pdf/src/Spiritix/Html2Pdf/Converter.php:188

Stack trace: 
#0 /var/www/public/audit-letter/index.php(22): Spiritix\Html2Pdf\Converter->convert()
#1 {main} thrown in /var/www/public/vendor/spiritix/php-chrome-html2pdf/src/Spiritix/Html2Pdf/Converter.php on line 188
```

With the Node Path commented out, my output looks like this:

```
Fatal error:
    Uncaught Spiritix\Html2Pdf\ConverterException:
    Shell error: 127 in /var/www/public/vendor/spiritix/php-chrome-html2pdf/src/Spiritix/Html2Pdf/Converter.php:192

Stack trace:
#0 /var/www/public/audit-letter/index.php(22): Spiritix\Html2Pdf\Converter->convert()
#1 {main} thrown in /var/www/public/vendor/spiritix/php-chrome-html2pdf/src/Spiritix/Html2Pdf/Converter.php on line 192
```

Within the Ubuntu VM, I ran `sudo apt-get update && sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget` in order to fulfill all the Debian Requirements, but that hasn't changed anything.

Is there something I am doing wrong?

**Comment by spiritix** [comment]
Hi, 

The version with the custom node path specified is definitely correct, as Shell Error 127 usually means that the program could not be found.

Then regarding the ``spawn EACCES`` error, it looks like this is something Mac specific, never saw it before. Your code works just fine for me. Some users have found that running ``npm install`` (resp. ``composer install`` for this library) without sudo and/or executing ``chmod 777 node_modules/puppeteer/.local-chromium/linux-[XXX]/chrome-linux/*`` would resolve the issue.

If that doesn't help, you could try to install Puppeteer manually like this: ``npm i -g puppeteer --unsafe-perm``

Hope this helps.

**Comment by ethanbeyer** [comment]
I think it comes down to running it on a VM.

If I take this code and run it with my Mac's command line via `php index.php`, it will run as expected. Within a VM that mirrors the production environment, it does not work - that's where the `spawn EACCES` error comes to play.

I think this must come down to a permissions issue with either Node or Composer on the VM, but I'm not sure where to start.

It's not a big deal though, I think this is edge-case stuff.

**Comment by spiritix** [comment]
Maybe it's a Scotchbox related issue, on my custom Vagrant VM it's working fine. Have you tried the suggested fixes above?

**Comment by spiritix** [comment]
I just saw that another user experienced the same issue and was able to resolve it:

> Since chromium was installed on node_modules folder by npm install, the problem occurred me is UnhandledPromiseRejectionWarning: Error: spawn EACCES.
> 
> After investigation, I found that the chromium binary owned by someone who run composer install/npm install, with default mode 700 in my Ubuntu. but php scripts owned and run by others, www usually. I must change the owner and mode of executable binary manually.

**Comment by ethanbeyer** [comment]
ohhhhhh, that makes sense! Let me try that. Thanks!

**Comment by sawrubgupta** [comment]
> ohhhhhh, that makes sense! Let me try that. Thanks!

have you found anything, because code is working in local machine but on aws deployment, its showing same error, have you got anything ?

**Comment by codinglife456** [comment]
@sawrubgupta have you resolved the issue on your end? I am unable to run it on my server as well

**Comment by sawrubgupta** [comment]
Yes, just install chrominium in your aws machine, if it is elasticbeanstalk you can use .ebextension file to install chrominium, if ec2 then install it manually

**Comment by codinglife456** [comment]
@sawrubgupta did you also have to play around with the permissions for the spiritix vendor folder or the node folder? Also did you end up having to use the setNodePath or is it commented out ultimately? I will give it a try thanks!

**Comment by codinglife456** [comment]
@sawrubgupta I have installed chromium however i am still getting the same shell error 127 if node path isn't specified and shell error 126 if node path is specified
