### ISSUE TITLE
Binary Error ->  import getStdin from 'get-stdin'; ^^^^^^^^ SyntaxError: Unexpected identifier at Module._compile

### ISSUE THREAD

**Issue by bretvanhorn** [spiritix/php-chrome-html2pdf#63]
Hi-

Our PDF generation is suddenly failing on our staging server after working great for the last several months. I suspect this happened after we upgraded from Ubuntu 18 to 20, but I may be mistaken. 

We are running:

- Laravel 10.44
- PHP 8.2
- Node 18.19.1
- NPM 10.2.4
- Ubuntu 20.04.6 LTS
- "spiritix/php-chrome-html2pdf": "^1.7.5"

Here is the full error:

> Spiritix \ Html2Pdf\ ConverterException
Binary error: /home/forge/[...]/vendor/spiritix/php-chrome-html2pdf/index.js:11 import getStdin from 'get-stdin'; ^^^^^^^^ SyntaxError: Unexpected identifier at Module._compile (internal/modules/cjs/loader.js:723:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Function.Module.runMain (internal/modules/cjs/loader.js:831:12) at startup (internal/bootstrap/node.js:283:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

And the code we use:

```php
public function displayPdf($type, $content, $id) {
        $input = new StringInput();
        $input->setHtml($content);
        $converter = new Converter($input, new EmbedOutput());
        $converter->setOption('landscape', false);

        $converter->setOptions([
            'printBackground' => true,
            'displayHeaderFooter' => false,
            'mediaType' => 'screen',
        ]);

        $output = $converter->convert();
        $output->embed($type.'-'.$id.'.pdf');

    }
```

What I have tried:

- Installed and verified working Chrome on the command line via dpkg
- Updated the server software
- Updated packages

Any help is appreciated. I can't seem to find anyone with this exact error here or on the web, so I'm at a loss. Thanks.

**Comment by bretvanhorn** [comment]
Just an update, zeroing in on the cause, I think. I did some debugging from the vendor files and was able to output the chrome command so I could run it manually. The PDF content actually outputs, but there is a unix warning about the new headless mode above it, which I believe is causing the error. See below for the command and chain of output. I cannot see how to force this package to use Puppeteer 22 vs the current 21.5, but I believe 22 forces headless:new. I also tried to find a way to affect that in the config file for Puppeteer, but did not see it. Any guidance, again, is appreciated!

```bash
node "/home/forge/[redacted]/vendor/spiritix/php-chrome-html2pdf/src/Spiritix/Html2Pdf/../../../index" -o '{"landscape":false,"printBackground":true,"displayHeaderFooter":false,"mediaType":"screen"}'
```

>   Puppeteer old Headless deprecation warning:
>     In the near future `headless: true` will default to the new Headless mode
>     for Chrome instead of the old Headless implementation. For more
>     information, please see https://developer.chrome.com/articles/new-headless/.
>     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
>     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

```bash
%PDF-1.4
%����
1 0 obj
<</Creator (Chromium)
/Producer (Skia/PDF m121)
/CreationDate (D:20240216191726+00'00')
/ModDate (D:20240216191726+00'00')>>
endobj
3 0 obj
<</Length 0>> stream

endstream
endobj
2 0 obj
<</Type /Page
/Resources <</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]>>
/MediaBox [0 0 612 792]
/Contents 3 0 R
/StructParents 0
/Parent 4 0 R>>
endobj
4 0 obj
<</Type /Pages
/Count 1
/Kids [2 0 R]>>
endobj
5 0 obj
<</Type /Catalog
/Pages 4 0 R>>
endobj
xref
0 6
0000000000 65535 f
0000000015 00000 n
0000000202 00000 n
0000000155 00000 n
0000000365 00000 n
0000000420 00000 n
trailer
<</Size 6
/Root 5 0 R
/Info 1 0 R>>
startxref
467
%%EOF
```

**Comment by bretvanhorn** [comment]
Update: completely uninstalling and reinstalling/downgrading to v1.6.1 fixes the issue.

**Comment by thunder809** [comment]
Hello,
i have the same issue.

We are using your package for pdf generation in a magento2-module.
Node v18, same error, on the current version of the package (1.7.6).

I dont´t have more insights on the specific system an OS of the customer, as i only have very limited access.

Workaround with downgrade to version 1.6.4 worked for me.

**Comment by spiritix** [comment]
@thunder809 Did you try to use the latest version 1.7.6? This was a known issue on 1.7.5.
